import { OnDestroy } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Subject } from 'rxjs';
import { TranslateService } from '@ngx-translate/core';
import { NbAuthSocialLink } from '@nebular/auth';
import { NbDialogService } from '@nebular/theme';
import { APIModel } from '@dongkap/do-core';
import { HttpFactoryService } from '@dongkap/do-core';
import { SecurityResourceModel } from '@dongkap/do-core';
import { AuthTokenService } from '../../services/auth-token.service';
import { AuthForceService } from '../../services/auth-force.service';
import * as i0 from "@angular/core";
export declare class LoginPageComponent implements OnDestroy {
    private router;
    private dialogService;
    private translate;
    private authTokenService;
    private authForceService;
    private apiPath;
    private httpBaseService;
    private oauthResource;
    responseError: any;
    responseErrorCode: any;
    buttonLogin: boolean;
    showPassword: boolean;
    icon: string;
    private progress;
    protected progressDOM: HTMLElement;
    protected destroy$: Subject<any>;
    formGroup: FormGroup;
    private urlAuthorizeGoogle;
    socialLinks: NbAuthSocialLink[];
    constructor(router: Router, dialogService: NbDialogService, translate: TranslateService, authTokenService: AuthTokenService, authForceService: AuthForceService, apiPath: APIModel, httpBaseService: HttpFactoryService, oauthResource: SecurityResourceModel, route: ActivatedRoute);
    ngOnDestroy(): void;
    login(): void;
    onShowPassword(): void;
    get hasErrorUsername(): boolean;
    get hasSuccessUsername(): boolean;
    get hasErrorPassword(): boolean;
    get hasSuccessPassword(): boolean;
    onClickTermsConditions(): void;
    protected initProgress(): void;
    protected doneProgress(): void;
    protected setProgress(progress: number): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<LoginPageComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<LoginPageComponent, "do-login-page", never, {}, {}, never, never>;
}
