import { Injector, OnDestroy, TemplateRef } from '@angular/core';
import { OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Subject } from 'rxjs';
import { NbDialogRef, NbDialogService } from '@nebular/theme';
import { HttpBaseModel } from '@dongkap/do-core';
import { BaseComponent, DatatableColumn, DoToastrService, Keyword, Sort, SortProperties } from '@dongkap/do-shared';
import { JobPlacementService } from '../services/job-placement.service';
import { AssignmentGroupModel } from '../models/job-placement.model';
import * as i0 from "@angular/core";
export declare class JobPlacementEditPageComponent extends BaseComponent<any> implements OnInit, OnDestroy {
    injector: Injector;
    private router;
    private toastr;
    private dialogService;
    private jobPlacementService;
    loading: boolean;
    disabled: boolean;
    protected destroy$: Subject<any>;
    assignmentGroup: AssignmentGroupModel;
    businessPartner: any;
    reload: boolean;
    apiPath: HttpBaseModel;
    apiPathAdd: HttpBaseModel;
    apiPathDelete: HttpBaseModel;
    columns: DatatableColumn[];
    sort: Sort;
    sortsDefault: SortProperties[];
    keyword: Keyword;
    assignmentIds: any[];
    constructor(injector: Injector, router: Router, toastr: DoToastrService, dialogService: NbDialogService, jobPlacementService: JobPlacementService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    onAddAssignment(): void;
    onDeleteAssignmentDialog(data: any, dialog: TemplateRef<any>): void;
    onDeleteAssignment(ref: NbDialogRef<any>): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<JobPlacementEditPageComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<JobPlacementEditPageComponent, "do-job-placement-edit-page", never, {}, {}, never, never>;
}
