name: Dongkap Webpack CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Copy index.html to 404 html
      run: |
        cp ./dist/docs/index.html ./dist/docs/404.html

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: apps
        folder: dist
